export const EmptyString: string = ''
export const SiteName: string = 'kyo'
export const SvgPath: string = 'https://kanjivg.tagaini.net/kanjivg/kanji/'
export const ExpandMoreIcon: string =  '↓'
export const IJPostClient: string = 'IJPostClient'
export const IJPostStaticPathClient: string = 'IJPostStaticPathClient'
export const IJSubjectClient: string = 'IJSubjectClient'
export const IJSubjectStatiPathClient: string = 'IJSubjectStatiPathClient'