export const SiteName: string = 'kyo'
export const MdxPath: string = 'lib/mdx-kanji'
export const SvgPath: string = 'https://kanjivg.tagaini.net/kanjivg/kanji/'
export const ExpandMoreIcon: string =  '↓'
export const IJPostRepository: string = 'IJPostRepository'
export const IJPostListRepository: string = 'IJPostListRepository'
export const PostfixSummary: string = '_summary'